site_name: Introduction to running R, Python, and Julia in HPC

nav:
    - Overview: index.md
    - Python: 
      - Intro: python_intro.md
      - Load and run: python_load_run.md
    - Julia:
      - Intro: julia_intro.md
      - Load and run: julia_load_run.md
    - R: 
      - Intro: r_intro.md
      - Load and run: r_load_run.md

theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    features: 
        - content.tabs.link
        
extra:
    feature:
        tabs: true

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      

