site_name: Introduction to R, MATLAB, and Julia in HPC
repo_url: https://github.com/UPPMAX/R-matlab-julia-HPC
docs_dir: docs-mk/
edit_uri: blob/main/docs-mk/

nav:
    - Overview: index.md
    - R: 
      - Schedule: r/schedule.md
      - Intro: r/intro/README.md
      - Load and run: r/load_run.md
      - RStudio: r/rstudio.md
      - Summary: r/summary.md
    - MATLAB: 
      - Schedule: matlab/schedule.md
    - Julia:
      - Schedule: julia/schedule.md
      - Intro: julia/intro.md
      - Load and run: julia/load_run.md
      - Environments and packages: julia/environments_packages.md
      - The notebook Pluto: julia/notebook_pluto.md
    - Advanced: 
      - Schedule: advanced/schedule.md
      - Parallel: advanced/parallel.md

theme: 
    # It was decided to use material with the ReadTheDocs theme added on top of it,
    # https://github.com/UPPMAX/R-matlab-julia-HPC/blame/main/meeting_notes/20250829.md#L61
    #
    # No idea how to put the ReadTheDocs on top of this ...
    name: material
    #highlightjs: true   # with pygments the theme provides the palette
    #hljs_languages:
    #    - yaml
    #    - rust
    features: 
        - content.tabs.link
        - content.code.copy
        
extra:
    feature:
        tabs: true

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - smarty
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  #- pymdownx.snippets
  - pymdownx.superfences
  #- pymdownx.keys
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
      

