site_name: Introduction to R, MATLAB, and Julia in HPC
repo_url: https://github.com/UPPMAX/R-matlab-julia-HPC
docs_dir: docs-mk/
edit_uri: blob/main/docs-mk/

nav:
    - Overview: index.md
    - R: 
      - Schedule: r/schedule.md
      - Intro: r/intro/README.md
      - Load and run: r/load_run.md
      - RStudio: r/rstudio.md
      - Summary: r/summary.md
    - MATLAB: 
      - Schedule: matlab/schedule.md
      - Intro: matlab/intro-matlab.md
      - Load and run: matlab/load_runMatlab.md
      - MATLAB terminal and SLURM: matlab/slurmMatlab.md
      - MATLAB GUI and batch jobs: matlab/MatlabGUIslurm.md
    - Julia:
      - Schedule: julia/schedule.md
      - Intro: julia/intro.md
      - Load and run: julia/load_run.md
      - Environments and packages: julia/environments_packages.md
      - The notebook Pluto: julia/notebook_pluto.md
    - Advanced: 
      - Schedule: advanced/schedule.md
      - Parallel: advanced/parallel/README.md
    - Misc: 
      - Evaluations: evaluations/README.md
      - Lesson plans: lesson_plans/README.md
      - Reflections: reflections/README.md

theme: 
    name: readthedocs
    features: 
        - content.tabs.link
        - content.code.copy
        
extra:
    feature:
        tabs: true

extra_css:
   - css/extra.css

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - smarty
  - tables
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  #- pymdownx.snippets
  - pymdownx.superfences
  #- pymdownx.keys
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
      

