# Check that there is correct spelling in all files
name: Check spelling

# Check spelling on the 18th day of the month.
# 18th as the first letter of this repo is the 18th letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/check_spelling.yaml
      - README.md
      - '**.md'
      - .wordlist.txt
  pull_request:
    paths:
      - .github/workflows/check_spelling.yaml
      - README.md
      - '**.md'
      - .wordlist.txt
  schedule:
  - cron: "0 0 18 * *"

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4.2.0

      - name: Remove folders that do not care about spelling
        run: |
          rm -rf docs/evaluations
          rm -rf exercises
          rm -rf meeting_notes

      - name: Remove files that do not care about spelling (yet)
        run: |
          rm docs/advanced/MLR.md
          rm docs/julia/batch.md

      - uses: igsekor/pyspelling-any@v1.0.4
