# Check that there is correct spelling in all files
#
# Errors are reported via an Issue being created,
# instead of via en email to all repository Watchers
name: Check spelling

# Only run this on the main branch, or with Pull Requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4.2.0

      - name: Remove folders that do not care about spelling
        run: |
          rm -rf DevelopmentDesign
          rm -rf feedback

      - uses: igsekor/pyspelling-any@v1.0.4
