# Checks if the rst files are formatted correctly.
name: Check RST

# This job will always pass.

jobs:
  check_rst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install rstcheck
        run: pip install rstcheck

      - name: Check docs/python/packages.rst
        run: rstcheck docs/python/packages.rst || true
