# Checks if the rst files are formatted correctly.
name: Check RST

# Always run, it shold always pass
on:
  push:
  pull_request:

jobs:
  check_rst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install rstcheck with Sphinx support
        run: pip install sphinx rstcheck rstcheck[sphinx]

      - name: Check docs/python/packages.rst
        run: rstcheck --ignore-directives tabs,mermaid,dropdown,keypoints docs/python/packages.rst || true 

      - name: Check docs/python/isolated.rst
        run: rstcheck --ignore-directives tabs,mermaid,dropdown,keypoints docs/python/isolated.rst || true
