# Check that there is correct spelling in all files
#
# Errors are reported via an issue being created,
# instead of via en email to all repository Watchers
name: Check spelling

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4.2.0

      - name: Remove test file. Skip this test to test the spell checker :-)
        run: rm docs/r/testR.rst

      - name: Remove folders that do not care about spelling
        run: |
          rm -rf evaluations
          rm -rf meeting_notes

      - uses: igsekor/pyspelling-any@v1.0.4
