name: Check links

# Only run this on the main branch, or with Pull Requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_links:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Remove folders that need not to be checked
        run: rm -rf /docs/python/not_used/

      - uses: gaurav-nelson/github-action-markdown-link-check@v1


      # Cannot deal w	ith emails :-/
      #- uses: lycheeverse/lychee-action@v1.2.0
      #  with:
      #    #args: --verbose --exclude-mail './**/*.md' './**/*.html'
      #    fail: true
