# Check that there is correct spelling in all files
name: Check spelling

# Check spelling on the 18th day of the month.
# 18th as the first letter of this repo is the 18th letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/check_spelling.yaml
      - 'docs/**'
      - .wordlist.txt
  pull_request:
    paths:
      - .github/workflows/check_spelling.yaml
      - 'docs/**'
      - .wordlist.txt
  schedule:
  - cron: "0 0 18 * *"

jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4.2.0

      - name: Remove test file. Skip this test to test the spell checker :-)
        run: rm docs/r/testR.rst

      - name: Remove folders that do not care about spelling
        run: |
          rm -rf evaluations
          rm -rf meeting_notes

      - uses: igsekor/pyspelling-any@v1.0.4
