# Creates the Sphinx website
name: Create Sphinx website

on:
  push:
    branches:
      - main

jobs:
  create_sphinx_website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      # Install plantuml
      - name: Install OS package dependencies
        run: |
          sudo apt update
          sudo apt install plantuml
          sudo apt install npm
          #npm install mermaid
          npm install -g @mermaid-js/mermaid-cli
          #npm install markmap

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build website, show error log if fail
        run: |
            sphinx-build -n docs _build || (cat /tmp/sphinx-err-*.log && exit 1)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

