name: Docs
on: [push, pull_request]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      # Install plantuml
      - name: Install OS package dependencies
        run: |
          sudo apt update
          sudo apt install plantuml
          #sudo apt install npm
          #npm install mermaid
          npm install -g @mermaid-js/mermaid-cli
          #npm install markmap

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Sphinx build in non-nitpicky mode, if fails, show the error log
        run: sphinx-build docs _build || /tmp/sphinx-err-kxuvbc_i.log
      #- name: Sphinx builds in nitpicky mode
      #  run: sphinx-build -n docs _build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

