name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 19 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove folders that need not to be checked
        run: |
          rm -rf /docs/not_used/
          rm -rf /docs/python/not_used/
          rm -rf /docs/julia/not_used/
          rm -rf /docs/R/not_used/
          rm -rf /docs/matlab/not_used/

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          # Check all markdown, html and reStructuredText files in repo (default)
          args: --base docs/ --verbose --no-progress './**/*.rst'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
